# Generated by Django 4.1.5 on 2023-09-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0002_quote_discount_quote_shipping_charge_quote_sub_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax',
        ),
    ]
