# Generated by Django 4.1.5 on 2023-09-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0003_remove_quote_discount_remove_quote_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
