# Generated by Django 4.1.5 on 2023-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0004_quote_discount_quote_shipping_quote_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='tax',
            field=models.FloatField(default=0, verbose_name='Tax'),
        ),
    ]
