# Generated by Django 4.1.5 on 2023-10-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0005_lineitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('UNCONFIRMED', 'Unconfirmed')], default='UNCONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
