# Generated by Django 4.1.5 on 2023-10-24 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0007_alter_quote_discount_alter_quote_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoting.quote')),
            ],
        ),
    ]
