# Generated by Django 4.1.5 on 2023-09-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0002_invoicingfile_salesinvoicing_inputinvoicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinvoicing',
            name='creat_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='InputInvoicing_creat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inputinvoicing',
            name='invocing_file',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoicingfile', verbose_name='Invoicing File'),
        ),
        migrations.AlterField(
            model_name='inputinvoicing',
            name='update_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='InputInvoicing_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoicing',
            name='creat_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SalesInvoicing_creat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoicing',
            name='invocing_file',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoicingfile', verbose_name='Invoicing File'),
        ),
        migrations.AlterField(
            model_name='salesinvoicing',
            name='update_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SalesInvoicing_update_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
