# Generated by Django 4.1.5 on 2023-09-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_alter_inputinvoicing_creat_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='inputinvoicing',
            old_name='invocing_file',
            new_name='invoicing_file',
        ),
        migrations.RenameField(
            model_name='salesinvoicing',
            old_name='invocing_file',
            new_name='invoicing_file',
        ),
        migrations.RemoveField(
            model_name='inputinvoicing',
            name='name_of_supplier',
        ),
        migrations.RemoveField(
            model_name='salesinvoicing',
            name='name_of_supplier',
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(default='Unkown', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(default='Unkown', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(default='Unkown', max_length=50, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_file_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax File Number'),
        ),
        migrations.AddField(
            model_name='salesinvoicing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.client'),
        ),
        migrations.AlterField(
            model_name='invoicingfile',
            name='file',
            field=models.FileField(upload_to='InvoicingFile', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='inputinvoicing',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.supplier'),
        ),
    ]
