# Generated by Django 4.1.5 on 2023-09-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_supplier_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.TextField(default='Unkown', verbose_name='Company Name'),
        ),
    ]
