# Generated by Django 4.1.5 on 2023-09-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_client_aus_business_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(choices=[('Net30', 'Net 30 Days'), ('Net60', 'Net 60 Days'), ('NetEOM', 'Net End of Month')], default='Net30', max_length=50, verbose_name='Payment Terms'),
        ),
    ]
