# Generated by Django 4.1.5 on 2023-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_alter_client_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address_city',
            field=models.CharField(default='Unkown', max_length=50, verbose_name='Billing City'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address_postal_code',
            field=models.CharField(default='Unkown', max_length=20, verbose_name='Billing Postal Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address_state',
            field=models.CharField(choices=[('QLD', 'QLD'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('WA', 'WA'), ('SA', 'SA'), ('NT', 'NT'), ('TAS', 'TAS'), ('ACT', 'ACT')], default='QLD', max_length=3, verbose_name='Address State'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address_street',
            field=models.CharField(default='Unkown', max_length=255, verbose_name='Billing Street'),
        ),
    ]
