# Generated by Django 4.1.5 on 2023-09-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_remove_client_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputinvoicing',
            name='invoicing_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoicing due date'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='tax',
            field=models.FloatField(blank=True, null=True, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='salesinvoicing',
            name='invoicing_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoicing due date'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoicing.salesinvoicing'),
        ),
        migrations.AlterField(
            model_name='salesinvoicing',
            name='tax_rate',
            field=models.FloatField(default=0.1, verbose_name='Tax rate'),
        ),
    ]
