# Generated by Django 4.1.5 on 2023-09-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_alter_salesinvoicing_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputinvoicing',
            name='invoicing_file',
        ),
        migrations.AlterField(
            model_name='inputinvoicing',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='salesinvoicing',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total Price'),
        ),
    ]
