# Generated by Django 4.1.5 on 2023-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_remove_salesinvoicing_invoicing_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='billing_address_city',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Billing City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_address_postal_code',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='Billing Postal Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_address_street',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Billing Street'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.TextField(default='Unknown', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='Contact Phone'),
        ),
    ]
