# Generated by Django 4.1.5 on 2023-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_invoice_discount_invoice_shipping_invoice_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='tax',
            field=models.FloatField(default=0.1, verbose_name='Tax'),
        ),
    ]
