# Generated by Django 4.1.5 on 2023-09-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_alter_lineitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
