# Generated by Django 4.1.5 on 2023-09-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='Not Assigned', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default='Not Assigned', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default='Not Assigned', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default='Not Assigned', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default='Not Assigned', max_digits=10),
        ),
    ]
