# Generated by Django 4.1.5 on 2023-10-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_alter_invoice_discount_alter_invoice_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='tax',
            field=models.FloatField(default=0.0, verbose_name='Tax'),
        ),
    ]
