# Generated by Django 4.1.5 on 2023-10-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_alter_lineitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='tax',
            field=models.FloatField(verbose_name='Tax'),
        ),
    ]
