# Generated by Django 4.1.5 on 2023-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0028_alter_invoice_discount_alter_invoice_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
