# Generated by Django 4.1.5 on 2023-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0049_invoiceactiontoken_remove_inputinvoicing_creat_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
