# Generated by Django 4.1.5 on 2023-10-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0051_remove_invoicepayable_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepayable',
            name='status',
        ),
    ]
