# Generated by Django 4.1.5 on 2023-10-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0052_remove_invoicepayable_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoicePayable',
        ),
    ]
