# Generated by Django 4.1.5 on 2023-10-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0053_delete_invoicepayable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
