# Generated by Django 4.1.5 on 2023-09-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Payroll items type')),
                ('wage_items', models.CharField(max_length=128, verbose_name='Payroll items type')),
                ('notes', models.CharField(max_length=128, verbose_name='Payroll items type')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, verbose_name='Serial number')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('time', models.DateField(verbose_name='time')),
                ('CRN', models.CharField(max_length=128, verbose_name='CRN')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128, verbose_name='Gender')),
                ('department', models.CharField(max_length=128, verbose_name='Department')),
                ('Tax_ID', models.CharField(max_length=128, verbose_name='Tax ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tel')),
                ('bank_of_account', models.CharField(blank=True, max_length=128, null=True, verbose_name='Bank of Account')),
                ('account_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Account Number')),
                ('salary_item_amount', models.CharField(max_length=128, verbose_name='Salary item amount')),
                ('currency', models.CharField(blank=True, max_length=128, null=True, verbose_name='Currency')),
                ('total_wages', models.FloatField(verbose_name='Total wages')),
                ('payroll_items', models.ManyToManyField(to='payroll.payrollitems', verbose_name='Payroll item')),
            ],
        ),
    ]
