# Generated by Django 4.1.5 on 2023-09-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollitems',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Payroll items type'),
        ),
    ]
