# Generated by Django 4.1.5 on 2023-09-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrollitems_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_wages',
            field=models.FloatField(blank=True, help_text='The value of this field will be based on the payroll_ Automatic calculation of items field', null=True, verbose_name='Total wages'),
        ),
    ]
